@url = http://localhost:3000

### Main
GET {{url}}/test

### Get all tests
Get {{url}}/test/get

### Get One
# @prompt id
GET {{url}}/test/get/{{id}}

### Get me
GET {{url}}/test/me
core-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0MmM0NjJmZGRkZDIzY2Y5ZWRlMzQ2OCIsImlhdCI6MTY4MDYyMzE1MX0.v41Eo94mYNWqOsG338c8qNEq35cFwlcpbxqdswl8r9k 

### Get me - Incorrect token
GET {{url}}/test/me
core-access-token: asdsadasdas

### Get me - No Token
GET {{url}}/test/me

### Create Test
# @prompt tittle
POST {{url}}/test/post
Content-Type: application/json

{
    "title": "{{tittle}}"
}

### Create Test with no title
POST {{url}}/test/post
Content-Type: application/json

{}

### Create User
# @prompt username
POST {{url}}/test/signup
Content-Type: application/json

{
    "username": "{{username}}",
    "email": "{{username}}@gmail.com",
    "password": "123456"
}

### Login user
# @prompt username
POST {{url}}/test/signin
Content-Type: application/json

{
    "email": "{{username}}@gmail.com",
    "password": "123456"
}


### Edit Test
# @prompt id
# @prompt title
PUT {{url}}/test/edit/{{id}}
Content-Type: application/json

{
    "title": "{{title}}"
}

### Edit Test with empty object
# @prompt id
PUT {{url}}/test/edit/{{id}}
Content-Type: application/json

{}


### Delete Test
# @prompt id
DELETE {{url}}/test/delete/{{id}}
